### ISSUE TITLE
Fingerprinting results inaccurate for randomized canvas blockers

### ISSUE THREAD

**Issue by Hainish** [EFForg/panopticlick#16]
Some canvas fingerprinting blockers such as CanvasBlocker for Firefox randomize the result of canvas fingerprinting.  This makes the result of canvas fingerprinting look more unique than it actually is.

One way to mitigate this is to test for the canvas fingerprint twice, and see if there is a difference.  If there is, report the canvas fp to be "unknown"

**Comment by SahAssar** [comment]
Is there any sort of canvas/webgl hash that is regarded as "not a fingerprint" currently? I tried returning empty results from the normal canvas APIs and the webgl ones too (WebGLRenderingContext.readPixels and WebGL2RenderingContext.readPixels) but even returning empty values seem to be regarded as a fingerprint.

I'm guessing this is due to empty values being uncommon enough to be a identifying marker, right?

**Comment by Hainish** [comment]
@SahAssar every bit of information you leak can be given an entropic value and feed into your fingerprint.  From the perspective of a tracker, the fact that you have an empty fingerprint returned can be extremely telling if you're the only one using that method.  On the other hand, if you're in a pool of other users with empty fingerprints, this too can be assigned an entropy value.

**Comment by ishitatsuyuki** [comment]
What's the status on this?
